import { NextRequest, NextResponse } from 'next/server';
import { auth, hasPermission } from '@/lib/auth';
import dbConnect from '@/lib/db';
import Client from '@/models/Client';
import Invoice from '@/models/Invoice';
import FinanceSettings from '@/models/FinanceSettings';
import dayjs from 'dayjs';
import * as z from 'zod';

const generateSchema = z.object({
  billingPeriod: z.string().regex(/^\d{4}-\d{2}$/, 'Billing period must be in YYYY-MM format'),
});

export async function POST(req: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    // RBAC: Manager or Super Admin
    const isManager =
      (session.user as any).role === 'Super Admin' ||
      (session.user as any).role === 'Manager' ||
      (session.user as any).role === 'Admin';
    if (!isManager) {
      return NextResponse.json({ success: false, error: 'Forbidden' }, { status: 403 });
    }

    await dbConnect();
    const orgId = (session.user as any).organizationId;
    const body = await req.json();

    const parsedData = generateSchema.parse(body);
    const { billingPeriod } = parsedData;

    // Get active clients with retainer value > 0
    const activeClients = await Client.find({
      organizationId: orgId,
      status: 'active',
      monthlyRetainerValue: { $gt: 0 },
    });

    if (activeClients.length === 0) {
      return NextResponse.json({
        success: true,
        data: { generated: 0, skipped: 0, invoices: [] },
        message: 'No active clients with monthly retainer values found.',
      });
    }

    // Fetch settings
    let settings = await FinanceSettings.findOne({ organizationId: orgId });
    if (!settings) {
      settings = new FinanceSettings({
        organizationId: orgId,
        companyName: 'My Marketing Agency',
        invoicePrefix: 'INV',
        defaultPaymentDueDays: 7,
      });
      await settings.save();
    }

    const monthName = dayjs(billingPeriod, 'YYYY-MM').format('MMMM YYYY');
    const createdInvoices = [];
    let skippedCount = 0;
    let generatedCount = 0;

    // Get last invoice number to start sequence
    const lastInvoiceObj = await Invoice.findOne({ organizationId: orgId })
      .sort({ invoiceNumber: -1 })
      .select('invoiceNumber')
      .lean();

    const prefix = settings.invoicePrefix || 'INV';
    let nextNum = 1;

    if (lastInvoiceObj?.invoiceNumber) {
      const match = lastInvoiceObj.invoiceNumber.match(new RegExp(`${prefix}-(\\d+)`));
      if (match) {
        nextNum = parseInt(match[1], 10) + 1;
      } else {
        const fallbackMatch = lastInvoiceObj.invoiceNumber.match(/-(\d+)/);
        if (fallbackMatch) {
          nextNum = parseInt(fallbackMatch[1], 10) + 1;
        }
      }
    }

    for (const client of activeClients) {
      // Check if invoice already exists for this billingPeriod
      const existing = await Invoice.findOne({
        organizationId: orgId,
        clientId: client._id,
        invoiceType: 'retainer',
        billingPeriod,
      });

      if (existing) {
        skippedCount++;
        continue;
      }

      const invNumber = `${prefix}-${String(nextNum).padStart(4, '0')}`;
      nextNum++;

      const unitPrice = client.monthlyRetainerValue;
      const amount = unitPrice;
      const subtotal = amount;
      const totalAmount = amount;

      const invoiceDate = new Date();
      const dueDate = new Date();
      dueDate.setDate(invoiceDate.getDate() + (settings.defaultPaymentDueDays || 7));

      const newInvoice = new Invoice({
        organizationId: orgId,
        invoiceNumber: invNumber,
        clientId: client._id,
        businessName: client.businessName,
        billingAddress: {
          street: client.address?.street || '',
          city: client.address?.city || '',
          state: client.address?.state || '',
          pincode: client.address?.pincode || '',
          country: client.address?.country || 'India',
        },
        contactPerson: client.contactPerson,
        email: client.email,
        phone: client.phone,
        invoiceType: 'retainer',
        invoiceDate,
        dueDate,
        billingPeriod,
        lineItems: [
          {
            description: `Monthly Retainer — ${monthName}`,
            quantity: 1,
            unitPrice,
            amount,
          },
        ],
        subtotal,
        discountType: null,
        discountValue: 0,
        discountAmount: 0,
        gstApplicable: false,
        gstRate: 18,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 0,
        totalAmount,
        amountPaid: 0,
        amountDue: totalAmount,
        status: 'draft',
        isAutoGenerated: true,
        generatedFromRetainerMonth: billingPeriod,
        notes: settings.invoiceNotes || '',
        termsAndConditions: settings.invoiceTermsAndConditions || '',
      });

      await newInvoice.save();
      createdInvoices.push(newInvoice);
      generatedCount++;
    }

    return NextResponse.json({
      success: true,
      data: {
        generated: generatedCount,
        skipped: skippedCount,
        invoices: createdInvoices,
      },
      message: `Retainer invoices generated successfully: ${generatedCount} created, ${skippedCount} skipped.`,
    });
  } catch (error: any) {
    console.error('[INVOICES_GENERATE_RETAINER] Error:', error);
    if (error?.name === 'ZodError') {
      return NextResponse.json({ success: false, error: error.errors[0].message }, { status: 400 });
    }
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
