import mongoose, { Schema, Document, Model } from 'mongoose';
import { ILineItem } from './Quotation';

export interface IInvoice extends Document {
  organizationId: string;
  invoiceNumber: string;
  clientId: mongoose.Types.ObjectId;
  projectId?: mongoose.Types.ObjectId;
  businessName: string;
  billingAddress: {
    street?: string;
    city?: string;
    state?: string;
    pincode?: string;
    country?: string;
  };
  contactPerson: string;
  email: string;
  phone: string;
  invoiceType: 'retainer' | 'project' | 'milestone' | 'custom';
  invoiceDate: Date;
  dueDate: Date;
  billingPeriod?: string; // 'YYYY-MM'
  lineItems: ILineItem[];
  subtotal: number;
  discountType?: 'percentage' | 'fixed' | null;
  discountValue: number;
  discountAmount: number;
  gstApplicable: boolean;
  gstRate: number;
  cgstAmount: number;
  sgstAmount: number;
  igstAmount: number;
  totalAmount: number;
  amountPaid: number;
  amountDue: number;
  status: 'draft' | 'sent' | 'partially_paid' | 'paid' | 'overdue' | 'cancelled';
  notes?: string;
  termsAndConditions?: string;
  sentAt?: Date;
  isAutoGenerated: boolean;
  generatedFromRetainerMonth?: string; // 'YYYY-MM'
  createdBy?: mongoose.Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

const InvoiceLineItemSchema = new Schema({
  description: { type: String, required: true },
  quantity: { type: Number, required: true, default: 1 },
  unitPrice: { type: Number, required: true },
  amount: { type: Number, required: true },
});

const InvoiceSchema: Schema = new Schema(
  {
    organizationId: { type: String, required: true, index: true },
    invoiceNumber: { type: String, required: true },
    clientId: { type: Schema.Types.ObjectId, ref: 'Client', required: true },
    projectId: { type: Schema.Types.ObjectId, ref: 'Project' },
    businessName: { type: String, required: true },
    billingAddress: {
      street: { type: String },
      city: { type: String },
      state: { type: String },
      pincode: { type: String },
      country: { type: String, default: 'India' },
    },
    contactPerson: { type: String, required: true },
    email: { type: String, required: true, lowercase: true, trim: true },
    phone: { type: String, required: true },
    invoiceType: {
      type: String,
      enum: ['retainer', 'project', 'milestone', 'custom'],
      required: true,
    },
    invoiceDate: { type: Date, required: true, default: Date.now },
    dueDate: { type: Date, required: true },
    billingPeriod: { type: String },
    lineItems: [InvoiceLineItemSchema],
    subtotal: { type: Number, required: true, default: 0 },
    discountType: { type: String, enum: ['percentage', 'fixed', null], default: null },
    discountValue: { type: Number, default: 0 },
    discountAmount: { type: Number, default: 0 },
    gstApplicable: { type: Boolean, default: false },
    gstRate: { type: Number, default: 18 },
    cgstAmount: { type: Number, default: 0 },
    sgstAmount: { type: Number, default: 0 },
    igstAmount: { type: Number, default: 0 },
    totalAmount: { type: Number, required: true, default: 0 },
    amountPaid: { type: Number, required: true, default: 0 },
    amountDue: { type: Number, required: true, default: 0 },
    status: {
      type: String,
      enum: ['draft', 'sent', 'partially_paid', 'paid', 'overdue', 'cancelled'],
      default: 'draft',
    },
    notes: { type: String },
    termsAndConditions: { type: String },
    sentAt: { type: Date },
    isAutoGenerated: { type: Boolean, default: false },
    generatedFromRetainerMonth: { type: String },
    createdBy: { type: Schema.Types.ObjectId, ref: 'User' },
  },
  { timestamps: true }
);

InvoiceSchema.index({ organizationId: 1, invoiceNumber: 1 }, { unique: true });
InvoiceSchema.index({ organizationId: 1, status: 1 });
InvoiceSchema.index({ organizationId: 1, clientId: 1 });

const Invoice: Model<IInvoice> =
  mongoose.models.Invoice || mongoose.model<IInvoice>('Invoice', InvoiceSchema);

export default Invoice;
